[package]
name = "ik_creatures_v2"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.20.0", features = ["derive"] }
glam = { version = "0.29.2", features = ["bytemuck"] }
roots_core.path = "../roots/roots_core"
wgpu = "23.0.1"
